"""Agregar tabla archivos_adjuntos y quitar columna archivo_adjunto de tickets

Revision ID: 194807158c7d
Revises: 1b4bf6a9ca3d
Create Date: 2026-07-20 14:22:34.791120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194807158c7d'
down_revision: Union[str, Sequence[str], None] = '1b4bf6a9ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
