"""Agregar tabla archivos_adjuntos y quitar columna archivo_adjunto de tickets

Revision ID: 1b4bf6a9ca3d
Revises: 9da175b7aea7
Create Date: 2026-07-20 14:15:17.292251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4bf6a9ca3d'
down_revision: Union[str, Sequence[str], None] = '9da175b7aea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('nombre_guardado', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_guardado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivos_adjuntos')
    # ### end Alembic commands ###
