"""Eliminar columna archivo_adjunto de tickets

Revision ID: 63f5e20d28b8
Revises: 194807158c7d
Create Date: 2026-07-20 14:30:12.939670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63f5e20d28b8'
down_revision: Union[str, Sequence[str], None] = '194807158c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'archivo_adjunto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('archivo_adjunto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    # ### end Alembic commands ###
