"""Agregar archivo_adjunto a tickets

Revision ID: 9da175b7aea7
Revises: 44aca8b75c82
Create Date: 2026-07-19 20:30:14.223436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da175b7aea7'
down_revision: Union[str, Sequence[str], None] = '44aca8b75c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('archivo_adjunto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'archivo_adjunto')
    # ### end Alembic commands ###
